create or replace package agito.TU_Police is

  /*
  This package generated by Agito automatically to perform police table CRUD operations.
  29/05/2013 10:26:00
  */

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 29.05.2013 10:26:00
  -- ��lev                          : police tablosuna veri yazma i�lemi i�in yap�lm��t�r.
  -- %param p_rec                   : police tablosu veri listesidir.

  procedure add(p_rec in out nocopy TYT_Police);



  -- Yazar                          : HAMDI.SIPAHI
  -- Tarih                          : 20.11.2013 15:45:54
  -- ��lev                          : police tablosundaki verilerde de�i�iklik i�lemi i�in yap�lm��t�r.
  -- %param p_rec                   : police tablosu veri listesidir.
  -- %param p_Compare               : de�erin true olmas� durumunda gelen bilgiler ile eski veriler kontrol edilir
  --                                  verilerde de�i�iklik yoksa tablo update i�lemi yap�lmaz 
  procedure upd(p_rec     in out nocopy TYT_Police,
                p_Compare in boolean := true);

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 29.05.2013 10:26:00
  -- ��lev                          : police tablosundan veri silme i�lemi i�in yap�lm��t�r.
  -- %param p_polid                 : Poli�e kay�t numaras�d�r.

  procedure del(p_polid    in number,
                p_rowcount in boolean := true);

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 29.05.2013 10:26:00
  -- ��lev                          : police tablosundan veri okuma i�lemi i�in yap�lm��t�r.
  -- %param  p_polid                : Poli�e kay�t numaras�d�r.
  function read(p_polid in number) return TYT_Police;

  -- Yazar                          : ugur.kocak
  -- ��lev                          : policeNo alanina gore police kaydi doner
  function readByPoliceNo(p_policeNo varchar2) return TYT_Police;

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 29.05.2013 10:26:00
  -- ��lev                          : police tablosundan veri okuma i�lemi i�in yap�lm��t�r.
  -- %param  p_polid                : Poli�e kay�t numaras�d�r.
  -- %param p_zeylno                : Zeylname numaras�.
  -- %param r_pol                   : policeview tipinde veri bilgisi
  procedure readPolice(p_polid  in number,
                       p_zeylno in number,
                       r_pol    in out nocopy policeview%rowtype);

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 29.05.2013 10:26:00
  -- ��lev                          : Grup poli�esine ait bilgileri verir.
  -- %param  p_polid                : Poli�e kay�t numaras�d�r.
  function readGroupPolicy(p_polid in number) return TYT_Police;

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 29.05.2013 10:26:00
  -- ��lev                          : police tablosundan kayit varm� kontrol eder .
  -- %param  p_polid                : Poli�e kay�t numaras�d�r.

  function recordExists(p_polid in number) return boolean;

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 29.05.2013 10:26:00
  -- ��lev                          : police tablosundan kayit varm� kontrol eder .
  -- %param  p_polid                : Poli�e kay�t numaras�d�r.
  -- %param p_branskod              : Bran� kodu
  function recordExists(p_polid    in number,
                        p_branskod in varchar2) return boolean;

  function recordExistsByPoliceNo(p_policeNo varchar2) return boolean;

  function checkEntranceFee(p_msg   out varchar2,
                            p_polid in number) return number;

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 19.09.2013 10:26:00
  -- ��lev                          : Poli�eye ait baz� bilgileri sonpol �zerinden d�ner.
  -- %param p_grupid                : Grup poli�esine ait poli�e kay�t numaras�.
  -- %param p_polid                 : Kat�l�mc�ya ait poli�e kay�t numaras�.
  -- %param p_kimlikno              : Kat�l�mc�ya ait kimlik numaras�.
  -- %param p_sandikNo              : Kat�l�mc�ya ait sand�k numaras�.
  -- %param p_sicilNo               : Kat�l�mc�ya ait sicil numaras�.
  function getSonpol(p_grupid   in police.polid%type,
                     p_polid    in police.polid%type,
                     p_kimlikno in person.kimlikno%type,
                     p_sandikNo in sigortali.sandikno%type,
                     p_sicilNo  in sigortali.sicilno%type) return sigtypes.sonpolrec;

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 19.09.2013 10:26:00
  -- ��lev                          : Poli�eye ait baz� bilgileri sonpol �zerinden d�ner.
  -- %param p_polid                 : Kat�l�mc�ya ait poli�e kay�t numaras�.
  -- %param p_zeylNo                : Zeylname numaras�.
  -- %param p_katilimTip            : Kat�l�m tipi.
  -- %param p_yilprim               : Y�ll�k prim tutar�
  function getHesapPrim(p_polid      in number,
                        p_zeylNo     in number,
                        p_katilimTip in varchar2,
                        p_yilprim    in number) return number;

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 19.09.2013 10:26:00
  -- ��lev                          : Poli�eye ait zeyl bilgileri �zerinde net prim ve bsmv tutar�n� g�nceller.
  -- %param p_polid                 : Kat�l�mc�ya ait poli�e kay�t numaras�.
  -- %param p_hesapPrim             : Kat�l�mc�ya ait hesaplanan prim tutar�.
  -- %param p_bsmv                  : Vergi.
  procedure upd(p_polid     in number,
                p_hesapPrim in number,
                p_bsmv      in number);

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 24.09.2013 10:26:00
  -- ��lev                          : police tablosundan veri okuma i�lemi i�in yap�lm��t�r.
  -- %param p_polid                 : Poli�e kay�t numaras�d�r.
  -- %param r_pol                   : sonpol tipinde veri bilgisi
  procedure readPolice(p_polid in number,
                       r_pol   in out nocopy sonpol%rowtype);

  -- Yazar                          : Erg�n Altunbayrak
  -- Tarih                          : 01.11.2013 09:55:00
  -- ��lev                          : Verilen poli�e numaras�na ait police id yi d�nd�r�r
  -- %param p_polno                 : Poli�e numaras�d�r.
  -- return number                  : Poli�e Id
  function getPolIdByPolNumber(p_polNo in varchar2) return number;

  -- Yazar                          : Uygar Uluda�     
  -- Tarih                          : 18.03.2014
  -- ��lev                          : Polid ile poli�e no sorgulama
  -- %param p_polid                 : Police id
  function getPoliceNoByPolid(p_polid in number) return varchar2;

  -- Yazar                          : HAMDI.SIPAHI
  -- Tarih                          : 20.11.2013 15:45:54
  -- ��lev                          : t_police tablosundaki verilerde de�i�iklik varm� yokmu kontrol eder de�i�iklik yoksa true d�nd�r�r
  -- %param p_tytNew                : t_police tablosu veri listesidir.
  -- %param p_tytOld                : t_police tablosundaki verinin son halinidir.
  function equal(p_tytNew in tyt_POLICE,
                 p_tytOld in tyt_POLICE) return boolean;

  -- Yazar                          : HAMDI.SIPAHI
  -- Tarih                          : 20.11.2013 15:45:54
  -- ��lev                          : t_police tablosundaki karekter alanlar�n de�erlerini upper case olarak set eder
  -- %param p_rec                   : t_police tablosu veri listesidir.
  procedure upper(p_rec in out nocopy tyt_POLICE);

  -- Yazar                          : HAMDI.SIPAHI
  -- Tarih                          : 20.11.2013 15:45:54
  -- ��lev                          : t_police tablosundaki karekter alanlar�n de�erlerini lower case olarak set eder
  -- %param p_rec                   : t_police tablosu veri listesidir.
  procedure lower(p_rec in out nocopy tyt_POLICE);

  -- Yazar                          : HSIPAHI
  -- Tarih                          : 17.12.2013 10:26:00
  -- ��lev                          : Poli�e statusunu g�nceller.
  -- %param p_polid                 : Kat�l�mc�ya ait poli�e kay�t numaras�.
  -- %param p_status                : Poli�e stat� bilgisi
  -- %param p_substatus             : Poli�e alt stat� bilgisi
  procedure updStatus(p_polid     in number,
                      p_status    in varchar2,
                      p_substatus in varchar2);

  -- Yazar                           : Erg�n Altunbayrak
  -- Tarih                           : 26.02.2014
  -- ��lev                           : Poli�enin meri stat�s�nde olup olmad���n� sorgular
  -- %param p_polid                  : Poli�e kay�t numaras�
  -- %return boolean
  function isActivePolicy(p_polid in number) return boolean;

  -- Yazar                           : Kadir K�se
  -- Tarih                           : 06.04.2015
  -- ��lev                           : G�nderilen Type xml le d�n��t�r�
  Function GetXmlType(p_rec In tyt_police) Return xmltype;

  function generateUpdateScript(p_tytNew in tyt_POLICE,
                                p_tytOld in tyt_POLICE default null) return clob;

  -- Yazar                          : KAD�R K�SE
  -- Tarih                          : 24.12.2015
  -- ��lev                          : Poli�enin ilk vade Tarihini G�nceller
  -- %param p_polid                 : Kat�l�mc�ya ait poli�e kay�t numaras�.
  procedure updIlkVade(p_polid      in number,
                       p_IlkVadeTar In Date);

  function GetOksDurum(p_polid in number) return police.oksdurum%type deterministic
    parallel_enable;

  function getBransDsp(p_polid number) return varchar2;
  
  --------------------------------------------------------------------------------------------------------------------
  -- Poli�e nin iptal olup olmad���n� d�nd�ren fonksiyon
  -- %author                DUYGU �OLAK
  -- %crtDate               18.07.2022
  -- %updDate
  -- %usage                 Poli�e nin stat�s�n�n statmap tablosundaki kar��l���nda iptal durumu T ise
  -- %usage                 poli�e iptal edilmi� demektir, fonksiyon T d�nd�r�r. 
  -- %param  p_polid        Poli�e Numaras�
  function isCanceledPolicy(p_polid in number) return boolean;  

end;
/
